[package]
name = "dig-painting"
version = "0.1.0"
edition = "2021"

[dependencies]
egui_sdl2_gl = "*"
image = "*"
sdl2-sys = "^0.34"
colors-transform = "*"
rand="*"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image"]